spring:
  datasource:
    url: jdbc:mysql://mscalculate.chu0ky8wghd2.us-east-2.rds.amazonaws.com:3306/mscalculate
    username: docker
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      root: INFO
      com.zaxxer.hikari: DEBUG
      org.hibernate: DEBUG

  application:
    name: mscalculate

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

mq:
  queues:
    points: points