services:
  db:
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mscalculate
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
        - 3308
    networks:
        - bankms-network
  mscalculate:
      image: clarasantos/calculateimage
      restart: always
      build: C:\Users\mcbs\OneDrive\Documentos\mscalculate
      working_dir: /mscalculate
      environment:
          TZ: America/Sao_Paulo
          SPRING.DATASOURCE.URL: jdbc:mysql//db:3308/mscalculate
          SPRING.DATASOURCE.USERNAME: root
          SPRING.DATASOURCE.PASSOWRD: 1234
      ports:
          - 80:80
      command: mvn spring-boot:run
      depends_on:
          - db
      networks:
          - bankms-network
networks:
  bankms-network:
    driver: bridge
