services:
  db:
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mscustomer
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3309
    ports:
      - 3309:3309
    expose:
        - 3309
    networks:
        - bankms-network
  mscustomer:
      image: clarasantos/customerimage
      restart: always
      build: C:\Users\mcbs\OneDrive\Documentos\mscustomer
      working_dir: /mscustomer
      environment:
          TZ: America/Sao_Paulo
          SPRING.DATASOURCE.URL: jdbc:mysql//db:3309/mscustomer
          SPRING.DATASOURCE.USERNAME: root
          SPRING.DATASOURCE.PASSOWRD: 1234
      ports:
          - 81:81
      command: mvn spring-boot:run
      depends_on:
          - db
      networks:
          - bankms-network
networks:
  bankms-network:
    driver: bridge
