services:
  db:
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mspayment
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      - bankms-network
  mscustomer:
    image: clarasantos/paymentimage
    restart: always
    build: C:\Users\mcbs\OneDrive\Documentos\mspayment
    working_dir: /mspayment
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql//db:3309/mspayment
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSOWRD: 1234
    ports:
      - 82:82
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - bankms-network
networks:
  bankms-network:
    driver: bridge